update debian version in docker image and some other small changes

diff --git a/files/shell/functions b/files/shell/functions
--- a/files/shell/functions
+++ b/files/shell/functions
@@ -13,20 +13,20 @@ extract()
     exit 1
   else
     case $(echo $1 | tr '[:upper:]' '[:lower:]') in
-      *.tar.bz2)  tar -jxvf $1                     ;;
-      *.tar.gz)   tar -zxvf $1                     ;;
-      *.bz2)      bunzip2 $1                       ;;
-      *.dmg)      hdiutil mount $1                 ;;
-      *.gz)       gunzip $1                        ;;
-      *.tar)      tar -xvf $1                      ;;
-      *.tbz2)     tar -jxvf $1                     ;;
-      *.tgz)      tar -zxvf $1                     ;;
-      *.zip)      unzip $1                         ;;
-      *.pax)      cat $1 | pax -r                  ;;
-      *.pax.Z)    uncompress $1 --stdout | pax -r  ;;
-      *.rar)      unrar x $1                       ;;
-      *.z)        uncompress $1                    ;;
-      *)          echo "'$1' cannot be extracted"  ;;
+      *.tar.bz2)  tar -jxvf $1                        ;;
+      *.tar.gz)   tar -zxvf $1                        ;;
+      *.bz2)      bunzip2 $1                          ;;
+      *.dmg)      hdiutil mount $1                    ;;
+      *.gz)       gunzip $1                           ;;
+      *.tar)      tar -xvf $1                         ;;
+      *.tbz2)     tar -jxvf $1                        ;;
+      *.tgz)      tar -zxvf $1                        ;;
+      *.zip)      unzip $1                            ;;
+      *.pax)      cat $1 | pax -r                     ;;
+      *.pax.Z)    uncompress $1 --stdout | pax -r     ;;
+      *.rar)      unrar x $1                          ;;
+      *.z)        uncompress $1                       ;;
+      *)          >&2 echo "File cannot be extracted" ;;
     esac
   fi
 }
