updates

diff --git a/env/base/symlinks/config/zsh/functions/extract b/env/base/symlinks/config/zsh/functions/extract
--- a/env/base/symlinks/config/zsh/functions/extract
+++ b/env/base/symlinks/config/zsh/functions/extract
@@ -2,26 +2,28 @@
 
 # Extract archives
 
-if [ -z "$1" ]
-then
+if [ -z "$1" ]; then
   echo "Usage: extract <file>"
-  echo
-  echo "Supported types: tar.bz2 tar.gz tar tbz2 tgz zip"
   return 1
 fi
 
-if [ ! -f "$1" ]
-then
+if [ ! -f "$1" ]; then
   echo "'$1' is not a valid file" 1>&2
   return 1
 fi
 
-case $(echo "$1" | tr '[:upper:]' '[:lower:]') in
-  *.tar.bz2)  tar -jxvf "$1"                      ;;
-  *.tar.gz)   tar -zxvf "$1"                      ;;
-  *.tar)      tar -xvf  "$1"                      ;;
-  *.tbz2)     tar -jxvf "$1"                      ;;
-  *.tgz)      tar -zxvf "$1"                      ;;
-  *.zip)      unzip     "$1"                      ;;
-  *)          >&2 echo "File cannot be extracted" ;;
+case "$1" in
+  *.tar.bz2|*.tbz2) tar xjf "$1" ;;
+  *.tar.gz|*.tgz)   tar xzf "$1" ;;
+  *.tar.xz|*.txz)   tar xJf "$1" ;;
+  *.tar.Z)          tar xZf "$1" ;;
+  *.tar)            tar xf  "$1" ;;
+  *.bz2)            bunzip2 "$1" ;;
+  *.gz)             gunzip  "$1" ;;
+  *.rar)            unrar x "$1" ;;
+  *.zip)            unzip   "$1" ;;
+  *.7z)             7z x    "$1" ;;
+  *.Z)              uncompress "$1" ;;
+  *.xz)             unxz    "$1" ;;
+  *)                echo "'$1' cannot be extracted via extract()" 1>&2; return 1 ;;
 esac
